agents:
  - name: api-architect
    description: Designs and implements FastAPI endpoints, request validation, and API architecture
    context:
      - FastAPI routing and dependency injection
      - Pydantic models for request/response validation
      - RESTful API design patterns
      - WebSocket support for streaming responses
      - API versioning and documentation
      - Health checks and monitoring endpoints
      - Error handling and HTTP status codes

  - name: mcp-integration-expert
    description: Model Context Protocol server integration, tool development, and protocol compliance
    context:
      - MCP protocol specification and implementation
      - MCP server types (stdio, SSE, HTTP)
      - Tool discovery and registration in mao/mcp.py
      - Dynamic tool loading from external servers
      - Protocol validation and error handling
      - MCP server configuration management
      - LangChain-MCP adapter integration

  - name: agent-orchestrator
    description: Multi-agent coordination, LangGraph workflows, and agent state management
    context:
      - LangGraph state machines and workflows
      - Agent coordination patterns in mao/agents.py
      - StateGraph definition and node creation
      - Conditional routing and decision logic
      - Agent memory and context passing
      - Multi-agent communication protocols
      - Workflow error recovery and retries

  - name: llm-integration-specialist
    description: LLM provider integration, prompt engineering, and model management
    context:
      - LangChain integration (OpenAI, Anthropic, Ollama)
      - ChatAnthropic and ChatOpenAI implementations
      - Prompt templates and chain construction
      - Streaming responses and token management
      - Model selection and configuration
      - Function calling and tool use
      - LLM caching and optimization

  - name: vector-store-engineer
    description: Vector database operations, embeddings, and semantic search
    context:
      - Qdrant client operations in mao/storage.py
      - Collection creation and management
      - Document chunking and embedding strategies
      - Vector similarity search and filtering
      - Embedding model selection
      - Index optimization and performance tuning
      - Batch operations and data migration

  - name: rag-developer
    description: Retrieval-Augmented Generation pipeline development and optimization
    context:
      - RAG system implementation in mao/rag-system.py
      - Document preprocessing and chunking
      - Retrieval strategies and reranking
      - Context window management
      - Response generation with retrieved context
      - RAG evaluation and metrics
      - Hybrid search (vector + keyword)

  - name: async-python-expert
    description: Async/await patterns, performance optimization, and Python best practices
    context:
      - Modern async/await patterns (Python 3.11+)
      - asyncio event loop and concurrency
      - Type hints and Pydantic validation
      - uv package management workflow
      - Black formatting and Ruff linting
      - mypy type checking configuration
      - Performance profiling and optimization

  - name: database-specialist
    description: DuckDB analytics, data modeling, and storage optimization
    context:
      - DuckDB embedded database operations
      - SQL query optimization
      - Data modeling and schema design
      - Analytics queries and aggregations
      - Integration with vector store
      - Data export and import strategies
      - Performance tuning for large datasets

  - name: test-engineer
    description: Test strategy, pytest implementation, and quality assurance
    context:
      - pytest with pytest-asyncio for async tests
      - Mock LLM responses for deterministic tests
      - Integration testing for MCP servers
      - API endpoint testing with TestClient
      - Fixtures for common test scenarios
      - Code coverage with pytest-cov
      - CI/CD test automation
